application: commonconsensus-samsung
version: 1
runtime: python27
threadsafe: false 
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /(favicon\.ico)
  static_files: static/img/\1
  upload: static/img/(.*)

- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /CommonConsensus.swf
  static_files: static/CommonConsensus.swf
  upload: static/CommonConsensus.swf

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: .*
  script: main.app

libraries:
- name: markupsafe
  version: latest
- name: jinja2
  version: latest
- name: numpy 
  version: latest

skip_files:
- ^local/.*
- static/bootstrap*
- ^tests/.*
- ^.hg/.*
- ^.git/.*
- ^.idea/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
